apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow-server
        image: ghcr.io/mlflow/mlflow:v2.11.1
        ports:
        - containerPort: 5000
        env:
          - name: MLFLOW_BACKEND_STORE_URI
            value: "file:///mlflow/mlruns"
          - name: MLFLOW_ARTIFACT_ROOT
            value: "file:///mlflow/mlartifacts"
        command: ["mlflow", "server"]
        args: ["--backend-store-uri", "$(MLFLOW_BACKEND_STORE_URI)", "--default-artifact-root", "$(MLFLOW_ARTIFACT_ROOT)", "--host", "0.0.0.0"]
